# 1. 张量数据操作


## 1.1 导入 torch 库


① 虽然库为 PyTorch 库，但应该导入 torch，而不是 pytorch。


In [23]:
import torch

In [24]:
x = torch.arange(12)  # 初始化一个0-11的张量
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## 1.2 访问张量形状


① 可以通过张量的 shape 属性来访问张量的形状和张量中元素的总数。


In [25]:
x.shape  # 张量的形状

torch.Size([12])

In [26]:
x.numel()  # 张量中元素的总数

12

## 1.3 改变张量形状


① 要改变一个张量的形状而不改变元素数量和元素值，可以调用 reshape 函数。


In [27]:
x = torch.arange(12)
x = x.reshape(3, 4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

## 1.4 创建全 0、全 1 张量


① 使用全 0、全 1、其他常量或者从特定分布中随即采样的数字。


In [28]:
y = torch.zeros((2, 3, 4))
print(y)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [29]:
y = torch.ones((2, 3, 4))
print(y)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


## 1.5 创建指定值张量


① 通过提供包含数值的 Python 列表（或嵌套列表）来为所需张量中的每个元素赋予确定值。


In [30]:
y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])  # 二维
z = torch.tensor([[[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]])  # 三维
print(y)
print(z)
print(y.shape)
print(z.shape)

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])
tensor([[[2, 1, 4, 3],
         [1, 2, 3, 4],
         [4, 3, 2, 1]]])
torch.Size([3, 4])
torch.Size([1, 3, 4])


## 1.6 张量运算操作


① 常见的标准算术运算符(+、-、\*、/、和 \*\*)都可以被升级为按元素运算。


In [31]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x**y)  # ** 求幂运算

tensor([ 3.,  4.,  6., 10.])
tensor([-1.,  0.,  2.,  6.])
tensor([ 2.,  4.,  8., 16.])
tensor([0.5000, 1.0000, 2.0000, 4.0000])
tensor([ 1.,  4., 16., 64.])


② 对每个元素应用更多的计算。


In [32]:
x = torch.tensor([1.0, 2, 4, 8])
x = torch.exp(x)  # e的x次方
print(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])


## 1.7 张量合并操作


⑧ 可以把多个张量结合在一起。


In [33]:
x = torch.arange(12, dtype=torch.float32).reshape((3, 4))
y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
m = torch.cat((x, y), dim=0)  # 按行合并
n = torch.cat((x, y), dim=1)  # 按列合并
print(m)
print(n)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])
tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])


## 1.8 张量逻辑运算


① 通过逻辑运算符构建二元张量。


In [34]:
x = torch.arange(12, dtype=torch.float32).reshape((3, 4))
y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(x)
print(y)
print(x == y)  # 对应元素相等为 True，否则为 False

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])
tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])


## 1.9 张量累加运算


① 对张量中所有元素进行求和会产生一个只有一个元素的张量。


In [35]:
x = torch.arange(12, dtype=torch.float32).reshape((3, 4))
print(x.sum())

tensor(66.)


## 1.10 张量广播运算


① 即使形状不同，仍然可以通过调用广播机制(broadcasting mechanism) 来执行按元素操作。


In [36]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
print(a)
print(b)
print(a + b)  # a会复制出一个3*2的矩阵，b复制出一个3*2的矩阵，然后再相加，会得到一个3*2矩阵

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])
tensor([[0, 1],
        [1, 2],
        [2, 3]])


## 1.11 张量访问运算


① 可以用[-1]选择最后一个元素，可以用[1:3]选择第二个和第三个元素。


In [37]:
x = torch.arange(12, dtype=torch.float32).reshape((3, 4))
print(x[-1])
print(x[1:3])

tensor([ 8.,  9., 10., 11.])
tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


## 1.12 张量元素批量改写


① 除读取外，还可以通过指定索引来将元素写入矩阵。


In [38]:
x = torch.arange(12, dtype=torch.float32).reshape((3, 4))
x[1, 2] = 9
print(x)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])


② 为多个元素赋值相同的值，只需要索引所有元素，然后为它们赋值。


In [39]:
x = torch.arange(12, dtype=torch.float32).reshape((3, 4))
x[0:2, :] = 12
print(x)

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])


## 1.13 张量内存随运算而改变


① 运行一些操作会导致变量分配新内存


In [52]:
x = torch.arange(12, dtype=torch.float32).reshape((3, 4))
y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
before = id(y)
y = x + y
print(id(y) == before)  # 运行操作后，赋值后的y的id和原来的id不一样

True


②  X[:] = X + Y 或 X += Y 不会新分配内存，可以减少内存开销。


In [ ]:
x = torch.arange(12, dtype=torch.float32).reshape((3, 4))
y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
z = torch.zeros_like(y)
print("id(z):", id(z))
z[:] = x + y
print("id(z):", id(z))

id(z): 1782992600720
id(z): 1782992600720


In [42]:
x = torch.arange(12, dtype=torch.float32).reshape((3, 4))
y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
before = id(x)
x += y
print(id(x) == before)

True


## 1.14 张量转 Numpy


① 张量转 NumPy。


In [43]:
x = torch.arange(12, dtype=torch.float32).reshape((3, 4))
A = x.numpy()
B = torch.tensor(A)
print(type(A), type(B))

<class 'numpy.ndarray'> <class 'torch.Tensor'>


② 将大小为 1 的张量转为 Python 标量。


In [44]:
a = torch.tensor([3.5])
print(a)
print(a.item())
print(float(a))
print(int(a))

tensor([3.5000])
3.5
3.5
3
