In [1]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([2, 3, 4])

# 交集

In [3]:
np.intersect1d(arr1, arr2)

array([2, 3])

# 并集

In [4]:
np.union1d(arr1, arr2)

array([1, 2, 3, 4])

# 差集

In [5]:
np.setdiff1d(arr1, arr2),

(array([1]),)

# 对称差

In [6]:
np.setxor1d(arr1, arr2)

array([1, 4])

# 多数组

In [9]:
from functools import reduce
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([2, 3])
arr3 = np.array([3, 4])

In [11]:
reduce(np.intersect1d, [arr1, arr2, arr3])

array([3])