# Array Slicing(切片)


In [13]:
import numpy as np
import pandas as pd

# 规律

1. ,逗号分隔 行/列
2. :冒号分隔 当前行/列的范围
   1. start:end:interval
   2. 分割 包含 start,不包含 end,例如 1:3 代表前两个
   3. 单一个: 代表全部,[1,:][:,1]可以用来取单行/ lie
3. 当没有逗号时，代表至分割行
   1. 例如 1:3 代表 1-3 行


In [14]:
base_data = np.random.randint(1, 100, (4, 4))
print(base_data)

[[ 3 39 48 51]
 [ 8 31 41 74]
 [94 20 75 18]
 [66 13 32 52]]


# 第 1 行第 2 列


In [15]:
base_data[1, 2]

41

# [1,:] 第 2 行 列全部


In [16]:
base_data[1, :]

array([ 8, 31, 41, 74])

# [1:3] 第 2-3 行


In [17]:
base_data[1:3]

array([[ 8, 31, 41, 74],
       [94, 20, 75, 18]])

# [:,1] 行全部 第 2 列


In [18]:
base_data[:, 1]

array([39, 31, 20, 13])

# [:3,] 前两行 列全部


In [19]:
base_data[:3,]

array([[ 3, 39, 48, 51],
       [ 8, 31, 41, 74],
       [94, 20, 75, 18]])

# [1:3,1:] 子区域


In [20]:
base_data[1:3, 1:]

array([[31, 41, 74],
       [20, 75, 18]])

# [::3,::2] 行 interval=23 列 interval=2 的子区域


In [21]:
base_data[::3, ::2]

array([[ 3, 48],
       [66, 32]])

# 切片和内存


In [22]:
orign_array = np.random.randint(1, 100, (3, 4, 5))
# 切片后得到的新的数组section的base属性就是three_dimensional_array
three_dimensional_array_slice = orign_array[:]

In [25]:
# base属性中,存在着原数组
three_dimensional_array_slice.base is orign_array

True

In [26]:
three_dimensional_array_slice is orign_array

False