In [2]:
import numpy as np
import matplotlib.pyplot as plt

# 创建


## 数组


### 一维数组


In [72]:
# 生成随机数创建数组对象,产生10个$[0, 1)$范围的随机小数
random_rand_array = np.random.rand(10)
random_rand_array

array([0.18986713, 0.18952268, 0.04992458, 0.43304338, 0.73972968,
       0.97952114, 0.9390458 , 0.08414517, 0.96997486, 0.35830088])

In [73]:
# 产生10个$[1, 100)$范围的随机整数
randint_list = np.random.randint(1, 100, 10)
randint_list

array([48, 66, 92, 69, 54, 43, 15, 23, 78, 97])

In [74]:
# 产生10个“标准正态”分布随机数
randn_list = np.random.randn(10)
randn_list

array([ 0.67517458,  0.5477147 ,  0.25852971, -2.12557542,  0.88043619,
        0.97200584, -2.15681885, -0.67385968, -0.14173197, -0.77143966])

In [75]:
# 产生20个$\mu=50$，$\sigma=10$的正态分布随机数
random_normal_list = np.random.normal(50, 10, 20)
random_normal_list

array([46.38337095, 36.71002372, 44.55588414, 62.24786382, 52.63953201,
       42.1847084 , 48.90276548, 64.95134701, 52.17476101, 52.60871857,
       38.74506935, 54.18439527, 48.52657017, 33.45628185, 59.87867515,
       58.50412774, 51.79466502, 65.03023101, 54.89160708, 53.10921047])

In [76]:
# 使用array函数，通过list创建数组对象
simple_array = np.array([1, 2, 3, 4, 5])
simple_array

array([1, 2, 3, 4, 5])

In [77]:
# 使用arange函数，指定取值范围创建数组对象
range_array = np.arange(0, 20, 2)
range_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [78]:
# 用指定范围均匀间隔的数字创建数组对象
linspace_array = np.linspace(-5, 5, 101)
linspace_array

array([-5. , -4.9, -4.8, -4.7, -4.6, -4.5, -4.4, -4.3, -4.2, -4.1, -4. ,
       -3.9, -3.8, -3.7, -3.6, -3.5, -3.4, -3.3, -3.2, -3.1, -3. , -2.9,
       -2.8, -2.7, -2.6, -2.5, -2.4, -2.3, -2.2, -2.1, -2. , -1.9, -1.8,
       -1.7, -1.6, -1.5, -1.4, -1.3, -1.2, -1.1, -1. , -0.9, -0.8, -0.7,
       -0.6, -0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,
        0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.1,  1.2,  1.3,  1.4,  1.5,
        1.6,  1.7,  1.8,  1.9,  2. ,  2.1,  2.2,  2.3,  2.4,  2.5,  2.6,
        2.7,  2.8,  2.9,  3. ,  3.1,  3.2,  3.3,  3.4,  3.5,  3.6,  3.7,
        3.8,  3.9,  4. ,  4.1,  4.2,  4.3,  4.4,  4.5,  4.6,  4.7,  4.8,
        4.9,  5. ])

### 二维数组


In [79]:
two_dimensional_array1 = np.array([[1, 2, 3], [4, 5, 6]])
two_dimensional_array1

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
# 创建全是0的二维数组
two_dimensional_zero_array = np.zeros((3, 4))
two_dimensional_zero_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [81]:
# 创建全是1的二维数组
two_dimensional_ones_array = np.ones((3, 4))
two_dimensional_ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [82]:
# 创建满二维数组
two_dimensional_full_array = np.full((3, 4), 10)
two_dimensional_full_array

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [83]:
# 将一维数组变成二维数组
one_dimensional_to_two_dimensional_array = np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)
one_dimensional_to_two_dimensional_array

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
# 产生$[0, 1)$范围的随机小数构成的3行4列的二维数组
random_two_dimensional_array = np.random.rand(3, 4)
random_two_dimensional_array

array([[0.50000796, 0.30705034, 0.41966101, 0.65164131],
       [0.92001995, 0.3161148 , 0.42100908, 0.81737356],
       [0.82189163, 0.05637814, 0.39034176, 0.53846336]])

In [85]:
# $[1, 100)$范围的随机整数构成的3行4列的二维数组
random_int_two_dimensional_array = np.random.randint(1, 100, (3, 4))
random_int_two_dimensional_array

array([[49, 44, 93, 12],
       [15, 72, 82, 92],
       [ 9, 30, 37, 48]])

### 三维数组


In [86]:
# 创建随机的三维数组
three_dimensional_array = np.random.randint(1, 100, (3, 4, 5))
three_dimensional_array

array([[[58,  3,  5,  6, 79],
        [27, 20, 89, 22, 60],
        [90, 86, 49, 44, 42],
        [39, 86, 38, 37, 62]],

       [[42, 14, 47, 73,  8],
        [69, 88, 58, 37, 68],
        [53, 13, 75, 89, 62],
        [83, 49, 15, 85, 97]],

       [[27,  1, 44, 98, 91],
        [86, 19, 38, 34, 50],
        [ 1, 14, 45, 96, 89],
        [33, 22, 19, 27, 80]]])

In [87]:
# 读取图片获得对应的三维数组
image_three_dimensional_array = plt.imread("test.png")
image_three_dimensional_array

array([[[0.75686276, 0.54509807, 0.41568628],
        [0.7647059 , 0.54509807, 0.4117647 ],
        [0.7647059 , 0.5411765 , 0.40784314],
        ...,
        [0.89411765, 0.5254902 , 0.27058825],
        [0.89411765, 0.5294118 , 0.26666668],
        [0.89411765, 0.5294118 , 0.2627451 ]],

       [[0.7490196 , 0.54509807, 0.41960785],
        [0.75686276, 0.54509807, 0.41960785],
        [0.7607843 , 0.54509807, 0.41568628],
        ...,
        [0.89411765, 0.5254902 , 0.27450982],
        [0.89411765, 0.5294118 , 0.26666668],
        [0.8901961 , 0.5294118 , 0.2627451 ]],

       [[0.7411765 , 0.54509807, 0.42352942],
        [0.7529412 , 0.54901963, 0.42745098],
        [0.75686276, 0.54901963, 0.41960785],
        ...,
        [0.89411765, 0.5254902 , 0.27058825],
        [0.8901961 , 0.5254902 , 0.27058825],
        [0.89411765, 0.5254902 , 0.27058825]],

       ...,

       [[0.25882354, 0.54901963, 0.78039217],
        [0.2627451 , 0.5529412 , 0.78431374],
        [0.25882354, 0

## 矩阵

官方并不推荐使用 matrix 类而是建议使用二维数组，而且有可能在将来的版本中会移除 matrix 类


In [88]:
# 创建单位矩阵
identity_matrix = np.eye(4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [89]:
matrix1 = np.matrix("1 2 3; 4 5 6")
matrix1

matrix([[1, 2, 3],
        [4, 5, 6]])

In [90]:
matrix2 = np.asmatrix(np.array([[1, 1], [2, 2], [3, 3]]))
matrix2

matrix([[1, 1],
        [2, 2],
        [3, 3]])

In [91]:
# 获取矩阵对象对应的ndarray对象
matrix2.A

array([[1, 1],
       [2, 2],
       [3, 3]])

In [92]:
# 获取矩阵对象对应的扁平化后的对象
matrix2.A1

array([1, 1, 2, 2, 3, 3])

In [93]:
# 可逆矩阵的逆矩阵
matrix2.I

matrix([[0.03571429, 0.07142857, 0.10714286],
        [0.03571429, 0.07142857, 0.10714286]])

In [94]:
# 矩阵的转置
matrix2.T

matrix([[1, 2, 3],
        [1, 2, 3]])

In [95]:
matrix2.shape

(3, 2)

In [96]:
matrix2.size

6

# 统计

- sum()、mean()、std()、var()、min()、max()、argmin()、argmax()、cumsum()
- 求和、求平均、求标准差、求方差、找最大、找最小、求累积和


In [3]:
simple_array = np.array([1, 2, 3, 4, 5, 5, 4, 3, 2, 1])

## 求值/求索引


In [4]:
simple_array.sum()

30

In [5]:
simple_array.mean()

3.0

In [6]:
simple_array.max()

5

In [13]:
np.argmax(simple_array)

4

In [7]:
simple_array.min()

1

In [15]:
np.argmin(simple_array)

0

In [8]:
simple_array.std()

1.4142135623730951

In [9]:
simple_array.var()

2.0

In [10]:
simple_array.cumsum()

array([ 1,  3,  6, 10, 15, 20, 24, 27, 29, 30])

# 数组属性


In [105]:
# 随机的的三维数组
three_dimensional_array = np.random.randint(1, 100, (3, 4, 5))

In [106]:
# 数组的形状
three_dimensional_array.shape

(3, 4, 5)

In [107]:
# 数组数据类型
three_dimensional_array.dtype

dtype('int32')

In [108]:
# 大小
three_dimensional_array.size

60

In [109]:
# 数组维度
three_dimensional_array.ndim

3

In [110]:
# 数组单元素占用内存空间字节
three_dimensional_array.itemsize

4

In [111]:
# 数组数组所有元素占用内存空间字节
three_dimensional_array.nbytes

240

# 序列化


In [112]:
simple_array = np.array([1, 2, 3, 4, 5, 5, 4, 3, 2, 1])
# 序列化
simple_array.dump("simple_array-data")

In [113]:
simple_array_load = np.load("simple_array-data", allow_pickle=True)
simple_array_load

array([1, 2, 3, 4, 5, 5, 4, 3, 2, 1])

# 变换

- fill() 向数组中填充指定的元素。
- flatten() 将多维数组扁平化为一维数组。
- nonzero() 方法：返回非 0 元素的索引。
- round() 方法：对数组中的元素做四舍五入操作。
- astype()方法：拷贝数组，并将数组中的元素转换为指定的类型。
- sort() 方法：对数组进行就地排序。
- swapaxes()和 transpose()方法：交换数组指定的轴。\*


In [114]:
two_dimensional_array1 = np.array([[1, 2, 3], [4, 5, 6]])
two_dimensional_array1

array([[1, 2, 3],
       [4, 5, 6]])

In [115]:
# 对于二维数组，transpose相当于实现了矩阵的转置
two_dimensional_array1.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [116]:
two_dimensional_array1.swapaxes(0, 1)

array([[1, 4],
       [2, 5],
       [3, 6]])

# 增删改查


## 删


### 删除行


In [4]:
arr = np.arange(0, 12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
# 删除行
np.delete(arr, [1], axis=0)

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [6]:
np.delete(arr, [0, 2], axis=0)

array([[4, 5, 6, 7]])

In [10]:
np.delete(arr, slice(0, 2), axis=0)

array([[ 8,  9, 10, 11]])

### 删除列


In [15]:
np.delete(arr, [0], axis=1)

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [14]:
np.delete(arr, [1])

array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## 增


In [16]:
arr = np.arange(0, 12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### append

在尾部进行追加，要求维度匹配


In [17]:
np.append(arr, [[0, 0, 0, 0]], axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  0,  0,  0]])

In [18]:
np.append(arr, [[0], [0], [0]], axis=1)

array([[ 0,  1,  2,  3,  0],
       [ 4,  5,  6,  7,  0],
       [ 8,  9, 10, 11,  0]])

### insert

insert 比 append 要方便/强大


In [28]:
arr = np.arange(0, 12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
np.insert(arr, 1, [0, 0, 0, 0], axis=0)

array([[ 0,  1,  2,  3],
       [ 0,  0,  0,  0],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
# 索引为 1 的位置插入一行，值全为 0
np.insert(arr, 1, 0, axis=0)

array([[ 0,  1,  2,  3],
       [ 0,  0,  0,  0],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
np.insert(arr, 0, 0, axis=1)

array([[ 0,  0,  1,  2,  3],
       [ 0,  4,  5,  6,  7],
       [ 0,  8,  9, 10, 11]])

In [32]:
np.insert(arr, 1, [[0, 0, 0, 1], [0, 0, 0, 1]], axis=0)

array([[ 0,  1,  2,  3],
       [ 0,  0,  0,  1],
       [ 0,  0,  0,  1],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
# 尾部插入
np.insert(arr, arr.shape[0], 0, axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  0,  0,  0]])

## 改


### where 修改满足条件的数据


In [25]:
arr = np.array([1, 2, 3, 4])

In [22]:
# 如果元素大于2, 那么减去10; 否则扩大十倍
np.where(arr > 2, arr - 10, arr * 10)

array([10, 20, -7, -6])

In [26]:
# 如果元素大于2, 那么保持不变, 否则变成4
np.where(arr > 2, arr, 4)

array([4, 4, 3, 4])

### clip  设置上下限

In [29]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
# 小于2的换成2, 大于6的换成6
np.clip(arr, 2, 6)

array([2, 2, 3, 4, 5, 6, 6, 6])

### 扁平化

#### flatten

In [30]:
arr = np.arange(0, 12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#### delete/append 不指定 axis,会导致数组扁平化


In [19]:
arr = np.arange(0, 12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
np.delete(arr, [11])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
np.delete(arr, [10, 11])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.append(arr, 0)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0])

In [26]:
np.append(arr, [0, 0])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  0])

## 查

### argwhere
找出满足条件的元素对应的**索引**

In [28]:
arr = np.array([3, 4, 5, 6, 7])
np.argwhere(arr % 2 == 0)

array([[1],
       [3]], dtype=int64)

# 排序

## sort

In [41]:
arr = np.array([4, 2, 3, 6, 5, 1])
arr

array([4, 2, 3, 6, 5, 1])

In [42]:
# 从小到大
np.sort(arr)

array([1, 2, 3, 4, 5, 6])

## argsort

In [43]:
# 返回从小到大排序后，排序后数组中元素原本的位置索引
np.argsort(arr)

array([5, 1, 2, 0, 4, 3], dtype=int64)

## topN

In [44]:
# top3
np.sort(arr)[-3:]

array([4, 5, 6])

## partition 局部排序

np.partition(arr, n)

找出arr中第n + 1小的元素(将arr排序之后索引n的元素), 然后返回一个新数组
并将原来数组中第n + 1小的元素放在新数组索引为n的地方, 保证左边的元素比它小, 右边的元素比它大

In [46]:
arr = np.array([66, 15, 27, 33, 19, 13, 10])

In [47]:
np.partition(arr, 3)

array([15, 13, 10, 19, 27, 33, 66])

In [49]:
# 获取排序之后的索引
np.argpartition(arr, 3)

array([1, 5, 6, 4, 2, 3, 0], dtype=int64)

In [48]:
# 找到第2大的元素
np.partition(arr, -2)

array([13, 10, 27, 15, 19, 33, 66])