# 查看当前 pytorch 版本


In [11]:
import torch

print(torch.__version__)

2.1.1+cpu


# 矩阵创建


In [12]:
# 3x5 矩阵
torch.empty(3, 5)

tensor([[-7.8692e+05,  8.2957e-43,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [13]:
# 3x5 随机数
torch.rand(3, 5)

tensor([[0.0879, 0.7135, 0.7268, 0.4876, 0.0209],
        [0.9724, 0.7342, 0.9818, 0.1270, 0.5856],
        [0.4589, 0.4212, 0.2405, 0.9137, 0.2740]])

In [14]:
# 3x5 全零矩阵
torch.zeros(3, 5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [15]:
# 通过参数构建矩阵
x = torch.tensor([5, 5, 3])
print(x)

tensor([5, 5, 3])


In [16]:
# 矩阵变换，变换为5x3
x = x.new_ones(5, 3, dtype=torch.double)
torch.rand_like(x, dtype=torch.double)

tensor([[0.9267, 0.8815, 0.9263],
        [0.8218, 0.8739, 0.6169],
        [0.0422, 0.5405, 0.8540],
        [0.2338, 0.3582, 0.3903],
        [0.9369, 0.3305, 0.3359]], dtype=torch.float64)

In [17]:
# 矩阵大小
x.size()

torch.Size([5, 3])

# 加法


In [19]:
add_result = torch.rand(3, 5) + torch.rand(3, 5)
print(add_result)

tensor([[1.3776, 0.8189, 1.0902, 0.9895, 1.0952],
        [1.3026, 1.0556, 1.4435, 1.0717, 0.9067],
        [1.0829, 1.1312, 1.1369, 0.8606, 1.6943]])


# index


In [23]:
idx_test = torch.rand(3, 5)
print(idx_test)
idx_test[-1]

tensor([[0.2699, 0.7486, 0.3656, 0.9384, 0.0230],
        [0.7249, 0.8824, 0.3491, 0.4181, 0.8899],
        [0.5668, 0.3854, 0.3672, 0.9705, 0.2247]])


tensor([0.5668, 0.3854, 0.3672, 0.9705, 0.2247])

# 矩阵变换


In [34]:
# 创建4x4格式
transformation = torch.rand(4, 4)
# 变换为4x4格式
print(transformation.view(4, 4))
# 变换为2x8格式
print(transformation.view(2, 8))
# -1代表自适应， -1X8=2X8
print(transformation.view(-1, 8))

tensor([[0.6842, 0.7611, 0.5294, 0.0445],
        [0.7707, 0.3634, 0.1877, 0.9626],
        [0.6851, 0.7793, 0.4292, 0.9248],
        [0.5006, 0.7767, 0.2173, 0.6274]])
tensor([[0.6842, 0.7611, 0.5294, 0.0445, 0.7707, 0.3634, 0.1877, 0.9626],
        [0.6851, 0.7793, 0.4292, 0.9248, 0.5006, 0.7767, 0.2173, 0.6274]])
tensor([[0.6842, 0.7611, 0.5294, 0.0445, 0.7707, 0.3634, 0.1877, 0.9626],
        [0.6851, 0.7793, 0.4292, 0.9248, 0.5006, 0.7767, 0.2173, 0.6274]])


# 关联 Numpy


## tensor 转 Numpy

使用 numpy()方法，无缝切换为 numpy 数据


In [37]:
numpy_test = torch.rand(4, 4)
print(numpy_test)

print(numpy_test.numpy())
print(type(numpy_test.numpy()))

tensor([[0.6424, 0.9642, 0.6009, 0.6427],
        [0.9833, 0.2036, 0.3268, 0.8070],
        [0.9557, 0.9634, 0.4325, 0.8197],
        [0.1683, 0.3810, 0.4947, 0.2105]])
[[0.64241457 0.9642109  0.6009393  0.6426787 ]
 [0.98332465 0.20364547 0.32678938 0.8070436 ]
 [0.9556763  0.96341604 0.43245798 0.8196955 ]
 [0.16825008 0.38100004 0.49465042 0.2105084 ]]
<class 'numpy.ndarray'>


## Numpy 转 tensor

使用 from_numpy 方法，切换为 torch 数据


In [40]:
import numpy as np

numpy_array = np.ones(5)

torch.from_numpy(numpy_array)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)