# Array Slicing(切片)

In [39]:
import numpy as np
import pandas as pd

# 规律

1. ,逗号分隔 行/列
2. :冒号分隔 当前行/列的范围
   1.  start:end:interval 
   2.  分割 包含start,不包含end,例如1:3 代表前两个
   3.  单一个: 代表全部,[1,:][:,1]可以用来取单行/ lie
3.  当没有逗号时，代表至分割行
    1.  例如 1:3 代表1-3行

In [40]:
base_data=np.random.randint(1, 100, (4, 4))
print(base_data)

[[35 45 49 16]
 [ 7 36 61 38]
 [73 41 94 76]
 [36 99 75 44]]


# 第1行第2列

In [41]:
base_data[1,2]

61

#  [1,:] 第2行 列全部

In [42]:
base_data[1,:]

array([ 7, 36, 61, 38])

# [1:3] 第2-3行

In [43]:
base_data[1:3]

array([[ 7, 36, 61, 38],
       [73, 41, 94, 76]])

# [:,1] 行全部 第2列

In [50]:
base_data[:,1]

array([45, 36, 41, 99])

# [:3,] 前两行 列全部

In [45]:
base_data[:3,]

array([[35, 45, 49, 16],
       [ 7, 36, 61, 38],
       [73, 41, 94, 76]])

# [1:3,1:] 子区域 

In [46]:
base_data[1:3,1:]

array([[36, 61, 38],
       [41, 94, 76]])

# [::3,::2] 行interval=23 列interval=2 的子区域

In [47]:
base_data[::3,::2]

array([[35, 49],
       [36, 75]])