# Advanced Higher Mathematics


In [2]:
import numpy as np

# matrix


## trace of matrix


In [2]:
arr = np.random.randint(1, 5, size=(4, 4))
arr

array([[1, 2, 4, 2],
       [2, 1, 2, 4],
       [1, 4, 4, 1],
       [3, 2, 2, 4]])

In [3]:
np.trace(arr)

10

## trace of two matrix


In [6]:
arr1 = np.array([[0, 1],
                 [1, 0]])

arr2 = np.array([[1, 1],
                 [1, 1]])
# 先计算a和b的差,得出arr3
arr3 = arr1 - arr2
# 然后让arr3和arr3本身进行点乘
arr4 = arr3 @ arr3
np.trace(arr4)

2

## inverse matrix


In [7]:
a = np.array([[1, -2, 1],
              [0, 2, -1],
              [1, 1, -2]])
np.linalg.inv(a)

array([[ 1.        ,  1.        ,  0.        ],
       [ 0.33333333,  1.        , -0.33333333],
       [ 0.66666667,  1.        , -0.66666667]])

## Adjoint matrix


In [8]:
a = np.array([[1, -2, 1],
              [0, 2, -1],
              [1, 1, -2]])
a_inv=np.linalg.inv(a)
a_det = np.linalg.det(a)
print(a_det)
a_inv * a_det

-3.0000000000000004


array([[-3., -3., -0.],
       [-1., -3.,  1.],
       [-2., -3.,  2.]])

## Solving linear equations of multiple variables


In [13]:
a = np.array([[1, 2, 1], [2, -1, 3], [3, 1, 2]])
# 将右边的常数写下来，排成一个矩阵
b = np.array([7, 7, 18])
# 求解，将参数传进去
x = np.linalg.solve(a, b)
print(x)  # [ 7.  1. -2.]
# 验证
print(a @ x)  # [ 7.  7. 18.]

[ 7.  1. -2.]
[ 7.  7. 18.]


## matrix rank


In [11]:
i = np.eye(4)
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.linalg.matrix_rank(i)

4

## covariance matrix


In [3]:
a = np.array([170, 180, 175])
b = np.array([65, 80, 70])
np.cov([a, b])

array([[25.        , 37.5       ],
       [37.5       , 58.33333333]])

## correlation matrix


In [4]:
a = np.array([170, 180, 175])
b = np.array([65, 80, 70])
np.corrcoef([a, b])

array([[1.        , 0.98198051],
       [0.98198051, 1.        ]])

## Derivative


In [9]:
x = np.poly1d([2, 1, 1])
print(x)

   2
2 x + 1 x + 1


In [10]:
x1 = x.deriv()
print(x1)  # 4 x + 1

 
4 x + 1


In [11]:
# Derivative value
print(x1(3))  # 13

13


## generate an equation


In [14]:
x = np.poly1d([1, 1, 1, 1])
x


poly1d([1, 1, 1, 1])

In [15]:
x = np.poly1d([8, 0, 4, 3, 1, 0])
print(x)


   5     3     2
8 x + 4 x + 3 x + 1 x


In [16]:
print(x(3)) 
print(8 * 3 ** 5 + 4 * 3 ** 3 + 3 * 3 ** 2 + 3) 

2082
2082
